Add a options to fix ignore "expire within" error
yajra/pdo-via-oci8 pull request #148
Opened 2024-11-18 04:15 UTC by lijialong1313

This PR is want to be fix about this:

![save](https://github.com/user-attachments/assets/fb0e6fb1-0fbf-4a92-848c-49abd86d81dd)

This error is the same as "the password will expire within" but not ignore. So I write this to let different country use different localized oracle databases can ignore as same as the English version.

I am sorry that I do't use this in a long time, so make some error about the old pr.

2024-11-26 03:25 UTC, yajra requested changes

2024-11-26 03:25 UTC, yajra commented on src/Pdo/Oci8.php
> +            $flag = true;
Can we rename this to `$throwError` for easier review in the future time?

Other than this, the changes look good. Thanks!

2024-11-28 01:23 UTC, lijialong1313 commented on src/Pdo/Oci8.php
> +            $flag = true;
Yes, of course. I've renamed the variable $flag to $throwError as you recommended.

2024-11-28 08:29 UTC, yajra approved these changes

2024-11-28 08:29 UTC, merged

2024-11-28 08:33 UTC, yajra commented
Release on https://github.com/yajra/pdo-via-oci8/releases/tag/v3.5.0 🚀 Thanks!