Added support for oci_set_call_timeout function
yajra/pdo-via-oci8 pull request #85
Opened 2020-12-11 11:36 UTC by ognjenVlad

I am submitting PR as requested https://github.com/yajra/laravel-oci8/issues/621. Support for oci_set_call_timeout(https://www.php.net/manual/en/function.oci-set-call-timout.php) is added as requested.

2020-12-11 12:05 UTC, yajra requested changes

2020-12-11 12:05 UTC, yajra commented on src/Pdo/Oci8.php
> +    private function setCallTimeout($time_out)
Looks good but I think this should be a ` public` method. Thanks!

2020-12-11 12:14 UTC, ognjenVlad commented on src/Pdo/Oci8.php
> +    private function setCallTimeout($time_out)
Yeah, sorry, my bad, I will push changes in a moment

2020-12-11 12:20 UTC, merged

2020-12-11 12:30 UTC, yajra commented
Released on v2.2.0 🚀 Thanks!

2020-12-11 12:41 UTC, ognjenVlad commented
> Released on v2.2.0 🚀 Thanks!

Thank you! That was fast!

2022-01-14 17:03 UTC, mbackonja commented
@yajra It would be nice if you can merge this also to v3 (for PHP 8 support)