chore!: add missing property types and return types for PHP 8.1
yajra/pdo-via-oci8 pull request #95
Opened 2022-01-28 12:49 UTC by danielrona

This pull should fix a couple of bugs and implement PHP8.1 for the most, so far I've not run into any issues as of yet 

- yajra/laravel-oci8#692 
- yajra/pdo-via-oci8#87
- yajra/laravel-oci8#695

2022-01-31 02:47 UTC, yajra requested changes

2022-01-31 02:47 UTC, yajra commented on composer.json
> +        "ext-oci8": "*"
This was recently requested to be removed by some users. Please remove, thanks!

2022-01-31 02:49 UTC, yajra commented
I've fixed and added a PHP8.1 github action on master branch. Can you please rebase on master and check if tests are working? I cannot update to PHP8 & 8.1 yet so I can't check this thoroughly. Thanks!

2022-01-31 03:00 UTC, yajra commented on composer.json
> +        "ext-oci8": "*"
Nvm this review. Let's have this enforced. Thanks!

2022-02-03 03:52 UTC, yajra commented
@danielrona changes looks good and tests are passing.

Requesting review from other users. If no response in a week or two, will merge this. Thanks!

2022-02-09 02:48 UTC, yajra approved these changes

2022-02-16 13:37 UTC, X-Coder264 commented
@yajra Any plans to merge and tag a release with this soon? We've just deployed Laravel 9 + PHP 8.1 to prod and our Sentry is full of these deprecation messages now.

2022-02-16 14:06 UTC, yajra commented
Unfortunately, can't upgrade yet. if you can confirm that this is working then I guess I can release this asap.

2022-02-17 23:19 UTC, X-Coder264 commented
I can do some basic testing over the weekend and let you know if my code still works with these changes.

2022-04-01 23:52 UTC, robsontenorio commented
@X-Coder264 what branch do you use for Laravel 9 + PHP 8.1 ?

2022-05-10 07:39 UTC, merged

2022-05-10 07:40 UTC, yajra commented
Sorry for late checking, I am now finally able to use 8.1 and can confirm that deprecate warning were fixed. Will be included in the next release.

2022-05-12 01:33 UTC, yajra commented
Released on v3.2.1, thanks! 🚀